### ISSUE TITLE
Unable to instantiate receiver

### ISSUE THREAD

**Issue by monove** [elizabethrego/cordova-plugin-instabug#4]
Here's my recent crash log. Any suggestions?

```
--------- beginning of crash
05-30 20:12:47.640 E/AndroidRuntime(24414): FATAL EXCEPTION: main
05-30 20:12:47.640 E/AndroidRuntime(24414): Process: com.appname.private, PID: 24414
05-30 20:12:47.640 E/AndroidRuntime(24414): java.lang.RuntimeException: Unable to instantiate receiver com.instabug.library.network.InstabugNetworkReceiver: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2724)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.os.Looper.loop(Looper.java:148)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.app.ActivityThread.main(ActivityThread.java:5443)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at java.lang.reflect.Method.invoke(Native Method)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-30 20:12:47.640 E/AndroidRuntime(24414): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-30 20:12:47.640 E/AndroidRuntime(24414):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-30 20:12:47.640 E/AndroidRuntime(24414):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2719)
05-30 20:12:47.640 E/AndroidRuntime(24414):     ... 8 more
05-30 20:12:47.640 E/AndroidRuntime(24414):     Suppressed: java.lang.ClassNotFoundException: com.instabug.library.network.InstabugNetworkReceiver
05-30 20:12:47.640 E/AndroidRuntime(24414):         at java.lang.Class.classForName(Native Method)
05-30 20:12:47.640 E/AndroidRuntime(24414):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-30 20:12:47.640 E/AndroidRuntime(24414):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-30 20:12:47.640 E/AndroidRuntime(24414):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-30 20:12:47.640 E/AndroidRuntime(24414):         ... 10 more
05-30 20:12:47.640 E/AndroidRuntime(24414):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-30 20:12:51.066 E/AndroidRuntime(24574): FATAL EXCEPTION: main
05-30 20:12:51.066 E/AndroidRuntime(24574): Process: com.appname.private, PID: 24574
05-30 20:12:51.066 E/AndroidRuntime(24574): java.lang.RuntimeException: Unable to instantiate receiver com.instabug.library.network.InstabugNetworkReceiver: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2724)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.os.Looper.loop(Looper.java:148)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.app.ActivityThread.main(ActivityThread.java:5443)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at java.lang.reflect.Method.invoke(Native Method)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-30 20:12:51.066 E/AndroidRuntime(24574): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-30 20:12:51.066 E/AndroidRuntime(24574):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-30 20:12:51.066 E/AndroidRuntime(24574):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2719)
05-30 20:12:51.066 E/AndroidRuntime(24574):     ... 8 more
05-30 20:12:51.066 E/AndroidRuntime(24574):     Suppressed: java.lang.ClassNotFoundException: com.instabug.library.network.InstabugNetworkReceiver
05-30 20:12:51.066 E/AndroidRuntime(24574):         at java.lang.Class.classForName(Native Method)
05-30 20:12:51.066 E/AndroidRuntime(24574):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-30 20:12:51.066 E/AndroidRuntime(24574):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-30 20:12:51.066 E/AndroidRuntime(24574):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-30 20:12:51.066 E/AndroidRuntime(24574):         ... 10 more
05-30 20:12:51.066 E/AndroidRuntime(24574):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-31 16:14:10.081 E/AndroidRuntime(32208): FATAL EXCEPTION: main
05-31 16:14:10.081 E/AndroidRuntime(32208): Process: com.appname.private, PID: 32208
05-31 16:14:10.081 E/AndroidRuntime(32208): java.lang.RuntimeException: Unable to instantiate receiver com.instabug.library.network.InstabugNetworkReceiver: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2724)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.os.Looper.loop(Looper.java:148)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.app.ActivityThread.main(ActivityThread.java:5443)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at java.lang.reflect.Method.invoke(Native Method)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-31 16:14:10.081 E/AndroidRuntime(32208): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-31 16:14:10.081 E/AndroidRuntime(32208):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-31 16:14:10.081 E/AndroidRuntime(32208):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2719)
05-31 16:14:10.081 E/AndroidRuntime(32208):     ... 8 more
05-31 16:14:10.081 E/AndroidRuntime(32208):     Suppressed: java.lang.ClassNotFoundException: com.instabug.library.network.InstabugNetworkReceiver
05-31 16:14:10.081 E/AndroidRuntime(32208):         at java.lang.Class.classForName(Native Method)
05-31 16:14:10.081 E/AndroidRuntime(32208):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-31 16:14:10.081 E/AndroidRuntime(32208):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-31 16:14:10.081 E/AndroidRuntime(32208):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-31 16:14:10.081 E/AndroidRuntime(32208):         ... 10 more
05-31 16:14:10.081 E/AndroidRuntime(32208):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-31 16:14:15.647 E/AndroidRuntime( 7146): FATAL EXCEPTION: main
05-31 16:14:15.647 E/AndroidRuntime( 7146): Process: com.appname.private, PID: 7146
05-31 16:14:15.647 E/AndroidRuntime( 7146): java.lang.RuntimeException: Unable to instantiate receiver com.instabug.library.network.InstabugNetworkReceiver: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2724)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.os.Looper.loop(Looper.java:148)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.app.ActivityThread.main(ActivityThread.java:5443)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at java.lang.reflect.Method.invoke(Native Method)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-31 16:14:15.647 E/AndroidRuntime( 7146): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.instabug.library.network.InstabugNetworkReceiver" on path: DexPathList[[zip file "/data/app/com.appname.private-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.private-1/lib/arm, /vendor/lib, /system/lib]]
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2719)
05-31 16:14:15.647 E/AndroidRuntime( 7146):     ... 8 more
05-31 16:14:15.647 E/AndroidRuntime( 7146):     Suppressed: java.lang.ClassNotFoundException: com.instabug.library.network.InstabugNetworkReceiver
05-31 16:14:15.647 E/AndroidRuntime( 7146):         at java.lang.Class.classForName(Native Method)
05-31 16:14:15.647 E/AndroidRuntime( 7146):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-31 16:14:15.647 E/AndroidRuntime( 7146):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-31 16:14:15.647 E/AndroidRuntime( 7146):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-31 16:14:15.647 E/AndroidRuntime( 7146):         ... 10 more
05-31 16:14:15.647 E/AndroidRuntime( 7146):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by elizabethrego** [comment]
Yes - spoke to Instabug support and multidexing needs to be enabled. 

I think if you combine with this plugin the error will go away: https://github.com/jwall149/cordova-multidex

**Comment by monove** [comment]
I already have that installed - your plugin requires it. This issue issue exists even with it installed.
